Bugfix: Iams find clinic button modification
Kinship-Partners-Inc/barkibu-web-widget pull request #37
Opened 2022-06-01 17:29 UTC by h4hany

# Human understandable Feature/Bugfix Title

## Why ?
_Here comes the Human understandable reason to why is this PR needed_
- Link to Basecamp User Story [[IAMS] User Journey From AI Vet to Find A Clinic](https://3.basecamp.com/3934852/buckets/27250433/todos/4924687490/edit?replace=true)
- Link to Sentry Issue?

## Changes
_Here comes the description of the changes involved a bit more technically._

## Checklist
- [ ] Tests added/updated
- [ ] Documentation updated
- [ ] ChangeLog updated

## How/What to test [Optional]
_Example: the path where the bug happened, so when testing we can see the error occurring 
and how it's not happening anymore after this fix_

## Upgrade Deployment Instructions [Optional]
_Here come the specific instructions to upgrade an existing instance (env vars, config vars...)_

2022-06-02 07:03 UTC, DCastroEspido requested changes
Hello, I think that you don't need findClinicButtonInChat, **you could use findAClinicEnabled to manage that**. 

But, if you want use a new feature flag, you have to take care of this: 

Firstly, the name should include enabled, following the nomenclature that we are using with the boolean feature flags. 

Secondly, you are having problems with the test, probably because you add a new feature flag and you didn't add to the test. To do that you have to add in mock_configuration.dart. 

Additionally, you have to add the new feature flag in the rest of the clients yaml files, if is not used they will have a value that disable this feature.

2022-06-09 17:11 UTC, malkovro requested changes

2022-06-09 17:11 UTC, malkovro commented on lib/src/chat/chat_component.html
> +                       *ngIf="isUrgent && findClinicButtonInChat"
```suggestion
                       *ngIf="isUrgent && findClinicButtonInChatEnabled"
```

2022-06-10 06:19 UTC, malkovro commented
The other more recent PR https://github.com/Kinship-Partners-Inc/barkibu-web-widget/pull/43 seems to be doing the same but using an existing flag. What is the behaviour that we want ? One single flag to toggle the FindAClinic feature on both screen or two distinct ones ?

2022-06-10 11:17 UTC, merged